export const siteUrl = "https://ljp.my.id";

export const seoKeywords = [
  "LJP",
  "LJP Furniture",
  "LJP Custom Furniture",
  "LJP Magelang",
  "LJP Furniture Magelang",
  "Custom Furniture Magelang",
  "Jasa Custom Furniture Magelang",
  "Furniture Custom Magelang",
  "Mebel Custom Magelang",
  "Pembuatan Furniture Custom Magelang",
  "Jasa Pembuatan Furniture Magelang",
  "Furniture Rumah Magelang",
  "Furniture Minimalis Magelang",
  "Furniture Modern Magelang",
  "Furniture Premium Magelang",
  "Furniture Kayu Magelang",
  "Furniture Interior Magelang",
  "Kitchen Set Magelang",
  "Kitchen Set Custom Magelang",
  "Kitchen Set Minimalis Magelang",
  "Kitchen Set Modern Magelang",
  "Lemari Custom Magelang",
  "Lemari Minimalis Magelang",
  "Lemari Pakaian Custom Magelang",
  "Lemari Bawah Tangga Custom Magelang",
  "Meja Kerja Custom Magelang",
  "Meja Belajar Custom Magelang",
  "Meja TV Custom Magelang",
  "Meja Makan Custom Magelang",
  "Meja Kantor Custom Magelang",
  "Meja Meeting Custom Magelang",
  "Rak TV Custom Magelang",
  "Rak Buku Custom Magelang",
  "Rak Display Custom Magelang",
  "Furniture Kantor Magelang",
  "Interior Kantor Magelang",
  "Furniture Workspace Magelang",
  "Furniture Cafe Magelang",
  "Furniture Restoran Magelang",
  "Meja Cafe Custom Magelang",
  "Kursi Cafe Custom Magelang",
  "Interior Cafe Magelang",
  "Furniture Hotel Magelang",
  "Furniture Villa Magelang",
  "Furniture Homestay Magelang",
  "Jasa Interior Magelang",
  "Interior Rumah Magelang",
  "Interior Minimalis Magelang",
  "Interior Modern Magelang",
  "Custom Furniture Jawa Tengah",
  "Jasa Furniture Jawa Tengah",
  "Furniture Custom Jawa Tengah",
  "Furniture Sesuai Ukuran",
  "Furniture Sesuai Kebutuhan",
  "Furniture Custom Berkualitas",
  "Furniture Custom Premium",
  "Furniture Handmade Magelang",
  "Tempat Bikin Furniture Custom Magelang",
  "Tempat Bikin Kitchen Set Magelang",
  "Tempat Bikin Lemari Custom Magelang",
  "Tempat Bikin Meja Custom Magelang",
  "Jasa Pembuatan Kitchen Set Magelang",
  "Jasa Pembuatan Lemari Custom Magelang",
  "Jasa Pembuatan Furniture Rumah Magelang",
  "Jasa Pembuatan Furniture Kantor Magelang",
  "Jasa Pembuatan Furniture Cafe Magelang",
  "Furniture Modern Minimalis Magelang",
  "Furniture Luxury Magelang",
  "Furniture Kayu Premium Magelang",
  "Custom Furniture Modern Magelang"
];

export const primarySeoKeywords = [
  "LJP Custom Furniture Magelang",
  "custom furniture Magelang",
  "jasa custom furniture Magelang",
  "furniture custom Magelang",
  "kitchen set Magelang",
  "lemari custom Magelang",
  "meja custom Magelang",
  "furniture kantor Magelang",
  "furniture cafe Magelang",
  "jasa interior Magelang"
];

export const defaultSeo = {
  title: "LJP Custom Furniture Magelang | Jasa Furniture Custom, Kitchen Set & Lemari",
  description:
    "LJP Custom Furniture Magelang melayani jasa pembuatan furniture custom, kitchen set, lemari, meja, rak TV, furniture kantor, cafe, restoran, hotel, villa, dan interior custom di Magelang serta Jawa Tengah.",
  image:
    "https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=1200&q=82",
  keywords: seoKeywords
};

export const serviceCatalog = [
  "Custom furniture Magelang",
  "Kitchen set custom Magelang",
  "Lemari pakaian custom Magelang",
  "Lemari bawah tangga custom Magelang",
  "Meja kerja custom Magelang",
  "Meja belajar custom Magelang",
  "Meja TV custom Magelang",
  "Meja makan custom Magelang",
  "Meja kantor custom Magelang",
  "Meja meeting custom Magelang",
  "Rak TV custom Magelang",
  "Rak buku custom Magelang",
  "Rak display custom Magelang",
  "Furniture kantor Magelang",
  "Furniture cafe dan restoran Magelang",
  "Furniture hotel, villa, dan homestay Magelang",
  "Interior rumah, kantor, dan cafe Magelang"
];
